from robo_ai.exception.api_error import ApiError


class NotAuthorizedError(ApiError):
    pass
